In [ ]:
import numpy as np
import pandas as pd

from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv("/content/Attrition - Attrition.csv")
df.head()

   Age Attrition  ... YearsSinceLastPromotion  YearsWithCurrManager
0   41       Yes  ...                       0                     5
1   49        No  ...                       1                     7
2   37       Yes  ...                       0                     0
3   33        No  ...                       3                     0
4   27        No  ...                       2                     2

[5 rows x 35 columns]

## UnderSampling

In [ ]:
## Encoding
lb = LabelEncoder()
df['Attrition'] = df['Attrition'].map({"Yes" : 1, "No" : 0})

cat_columns = df.select_dtypes(include="object").columns

for col in cat_columns:
  df[col] = lb.fit_transform(df[col])

In [ ]:
x = df.drop(columns= ['Attrition'])
y = df['Attrition']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=42)

In [ ]:
y_train.value_counts()

Attrition
0    913
1    189
Name: count, dtype: int64

In [ ]:
ruc = RandomUnderSampler(sampling_strategy='auto',random_state=0)

x_train, y_train = ruc.fit_resample(x_train, y_train)

In [ ]:
y_train.value_counts()

Attrition
0    189
1    189
Name: count, dtype: int64

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
dtc = DecisionTreeClassifier()

dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
y_pred = dtc.predict(x_test)

In [ ]:
accuracy_score(y_test, y_pred)

0.6277173913043478

oversampling

In [ ]:
df=pd.read_csv("/content/Attrition - Attrition.csv")
df.head()

   Age Attrition  ... YearsSinceLastPromotion  YearsWithCurrManager
0   41       Yes  ...                       0                     5
1   49        No  ...                       1                     7
2   37       Yes  ...                       0                     0
3   33        No  ...                       3                     0
4   27        No  ...                       2                     2

[5 rows x 35 columns]

In [ ]:
## Encoding
lb = LabelEncoder()
df['Attrition'] = df['Attrition'].map({"Yes" : 1, "No" : 0})

cat_columns = df.select_dtypes(include="object").columns

for col in cat_columns:
  df[col] = lb.fit_transform(df[col])

In [ ]:
x = df.drop(columns= ['Attrition'])
y = df['Attrition']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=42)

In [ ]:
y_train.value_counts()

Attrition
0    913
1    189
Name: count, dtype: int64

In [ ]:
ros= RandomOverSampler()
x_ros_train,y_ros_train=ros.fit_resample(x_train,y_train)

In [ ]:
y_ros_train.value_counts()

Attrition
0    913
1    913
Name: count, dtype: int64

In [ ]:
x_ros_train,

## Oversampling

In [ ]:
df = pd.read_csv("/content/Attrition - Attrition.csv")
df.head()

In [ ]:
## Encoding
lb = LabelEncoder()
df['Attrition'] = df['Attrition'].map({"Yes" : 1, "No" : 0})

cat_columns = df.select_dtypes(include="object").columns

for col in cat_columns:
  df[col] = lb.fit_transform(df[col])

In [ ]:
x = df.drop(columns= ['Attrition'])
y = df['Attrition']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=42)

In [ ]:
y_train.value_counts()

In [ ]:
smote = SMOTE(random_state = 42)
x_train, y_train = smote.fit_resample(x_train, y_train)

In [ ]:
y_train.value_counts()

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

In [ ]:
y_pred = dtc.predict(x_test)
score = accuracy_score(y_test, y_pred)
print(score)